# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
instance_name = "MySQL on Ubuntu"
location = "flatrock"
space = "Default"
cloud = "HPE GreenLake VMaaS Cloud"
datastore = "gl-flatrock-G2i-01-Bs-1"
network = "EPG_VC_1128"
group = "Default"
resource_pool = "gl-flatrock-G2i-vm-01"
compute_folder = "ComputeFolder"
layout = "V107a MySQL on Ubuntu 20.04"
instance_type = "v107a-mysql-on-ubuntu"
service_plan = "G2i-medium"
environment = "Dev"
