# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
instance_name = "MySQL on Ubuntu"
location = "FTC06"
space = "Default"
cloud = "HPE GreenLake VMaaS Cloud"
datastore = "gl-ftc06-Bs-Vol4"
network = "Blue-Segment"
group = "Default"
resource_pool = "gl-ftc06-G2i-vm-02"
compute_folder = "ComputeFolder"
layout = "V107a MySQL on Ubuntu 18.04"
instance_type = "v107a-mysql-on-ubuntu"
service_plan = "G2i-medium"
environment = "dev"
